CSP-911 Admin Aan CalendarEventSearchResults
SkillsFundingAgency/das-admin-aan-web pull request #3
Opened 2023-07-28 08:00 UTC by MarkFCain

2023-08-15 21:13 UTC, DevenKShah requested changes
@MarkFCain Can we loose the domain project and use nuget package for shared components that are copied as is please, sorry for rework.

2023-08-15 21:13 UTC, DevenKShah commented on src/SFA.DAS.AdminAan.Domain/Constants/EventStatus.cs
> +    public static string Published => "Published";
Can this be converted to const?

2023-08-15 21:13 UTC, DevenKShah commented on src/SFA.DAS.AdminAan.Domain/OuterApi/Responses/CalendarEventSummary.cs
Do we need a domain project? Can all these be in the application?

2023-08-15 21:13 UTC, DevenKShah commented on src/SFA.DAS.Admin.Aan.Application/OuterApi/Regions/Calendar.cs
Why is this in Regions folder?

2023-08-17 12:48 UTC, MarkFCain commented on src/SFA.DAS.Admin.Aan.Application/OuterApi/Regions/Calendar.cs
error, removed

2023-08-17 12:48 UTC, MarkFCain commented on src/SFA.DAS.AdminAan.Domain/OuterApi/Responses/CalendarEventSummary.cs
moved to application

2023-08-17 12:48 UTC, MarkFCain commented on src/SFA.DAS.AdminAan.Domain/Constants/EventStatus.cs
> +    public static string Published => "Published";
yes

2023-08-21 07:34 UTC, DevenKShah reviewed
Domain project should be removed and CSS file to be restored to original format.

2023-08-21 14:31 UTC, DevenKShah submitted a review, later dismissed

2023-08-24 11:09 UTC, YuvrajPatil-DFE approved these changes

2023-08-24 13:25 UTC, merged